### ISSUE TITLE
config file has some issues: sticker list is empty

### ISSUE THREAD

**Issue by mohamedevv** [star-39/whatsapp_stickers_exporter#1]
Hi i tried many packages  and the same error every time 
and also i tried to copy your code for 'Install From Remote File ' still same issue some times its work fine and another times not
do u know any solution ? 
thank you.

E/MethodChannel#whatsapp_stickers_exporter(14996): Failed to handle method call
E/MethodChannel#whatsapp_stickers_exporter(14996): java.lang.RuntimeException: config file has some issues: sticker list is empty
E/MethodChannel#whatsapp_stickers_exporter(14996): 	at moe.star39.whatsapp_stickers_exporter.ConfigFileManager.getStickerPacks(ConfigFileManager.java:41)
E/MethodChannel#whatsapp_stickers_exporter(14996): 	at moe.star39.whatsapp_stickers_exporter.ConfigFileManager.addNewPack(ConfigFileManager.java:84)
E/MethodChannel#whatsapp_stickers_exporter(14996): 	at moe.star39.whatsapp_stickers_exporter.WhatsappStickersExporterPlugin.onMethodCall(WhatsappStickersExporterPlugin.kt:63)
E/MethodChannel#whatsapp_stickers_exporter(14996): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#whatsapp_stickers_exporter(14996): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#whatsapp_stickers_exporter(14996): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#whatsapp_stickers_exporter(14996): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#whatsapp_stickers_exporter(14996): 	at android.os.Handler.handleCallback(Handler.java:883)
E/MethodChannel#whatsapp_stickers_exporter(14996): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/MethodChannel#whatsapp_stickers_exporter(14996): 	at android.os.Looper.loop(Looper.java:214)
E/MethodChannel#whatsapp_stickers_exporter(14996): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#whatsapp_stickers_exporter(14996): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#whatsapp_stickers_exporter(14996): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#whatsapp_stickers_exporter(14996): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/MethodChannel#whatsapp_stickers_exporter(14996): Caused by: java.lang.IllegalStateException: sticker list is empty
E/MethodChannel#whatsapp_stickers_exporter(14996): 	at moe.star39.whatsapp_stickers_exporter.ContentFileParser.readStickerPack(ContentFileParser.java:131)
E/MethodChannel#whatsapp_stickers_exporter(14996): 	at moe.star39.whatsapp_stickers_exporter.ContentFileParser.readStickerPacks(ContentFileParser.java:43)
E/MethodChannel#whatsapp_stickers_exporter(14996): 	at moe.star39.whatsapp_stickers_exporter.ContentFileParser.parseStickerPacks(ContentFileParser.java:24)
E/MethodChannel#whatsapp_stickers_exporter(14996): 	at moe.star39.whatsapp_stickers_exporter.ConfigFileManager.getStickerPacks(ConfigFileManager.java:39)
E/MethodChannel#whatsapp_stickers_exporter(14996): 	... 13 more
[log] Instance of 'WhatsappStickersException'

**Comment by barissemerci** [comment]
Same error message. How can i solve this error?
